(format t "(+ 5 4) values to: ~d ~%" (+ 5 4))
(format t "(- 5 4) values to: ~d ~%" (- 5 4))
(format t "(* 5 4) values to: ~d ~%" (* 5 4))
(format t "(/ 5 4) values to: ~d ~%" (/ 5 4))
(format t "(/ 5 4.0) values to: ~d ~%" (/ 5 4.0))
(format t "(expt 2 3) values to: ~d ~%" (expt 2 3))
(format t "(sqrt 81) values to: ~d ~%" (sqrt 81))
(format t "(log 16 2) values to: ~d ~%" (log 16 2))
(format t "(max 5 4) values to: ~d ~%" (max 5 4))
(format t "(min 5 4) values to: ~d ~%" (min 5 4))
(format t "(floor 5.4) values to: ~d ~%" (floor 5.4))
(format t "(ceiling 5.4) values to: ~d ~%" (ceiling 5.4))
(format t "(oddp 5) values to: ~d ~%" (oddp 5))
(format t "(evenp 5) values to: ~d ~%" (evenp 5))
(format t "(eq 20 (* 4 5)) values to: ~d ~%" (eq 20 (* 4 5)))
